default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: CoursesApp_development

test:
  <<: *default
  database: CoursesApp_test

production:
  <<: *default
  database: CoursesApp_production
  username: CoursesApp
  password: <%= ENV['COURSESAPP_DATABASE_PASSWORD'] %>
